#!/bin/bash

echo "🚀 Starting XAMPP..."
sudo /opt/lampp/lampp start

echo "🔥 Starting Laravel server..."
php artisan serve > storage/logs/laravel.log 2>&1 & echo $! > laravel.pid

echo "⚡ Starting Vite..."
npm run dev > storage/logs/vite.log 2>&1 & echo $! > vite.pid

echo "✅ Environment started!"


